// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKZZOScO40ZsPO4TVVVeuwkTNXYSr5HeI',
    appId: '1:1033082353842:web:48f59d2be6c92e7145f1ab',
    messagingSenderId: '1033082353842',
    projectId: 'sangathan-70b74',
    authDomain: 'sangathan-70b74.firebaseapp.com',
    storageBucket: 'sangathan-70b74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMG2pFnDoQznvvY4-OHgCUeJFUL3yAl48',
    appId: '1:1033082353842:android:0ccac22003c71e1145f1ab',
    messagingSenderId: '1033082353842',
    projectId: 'sangathan-70b74',
    storageBucket: 'sangathan-70b74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVpMMzRxXKr6zpgmjwVSQ_2RSFesT0q8U',
    appId: '1:1033082353842:ios:4ac17c1b6f039d3945f1ab',
    messagingSenderId: '1033082353842',
    projectId: 'sangathan-70b74',
    storageBucket: 'sangathan-70b74.appspot.com',
    iosClientId: '1033082353842-erre686defk556ln96l0s5fp3ps8dh23.apps.googleusercontent.com',
    iosBundleId: 'com.app.sangathan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVpMMzRxXKr6zpgmjwVSQ_2RSFesT0q8U',
    appId: '1:1033082353842:ios:2af45f3ffe0d903745f1ab',
    messagingSenderId: '1033082353842',
    projectId: 'sangathan-70b74',
    storageBucket: 'sangathan-70b74.appspot.com',
    iosClientId: '1033082353842-anmub2ojs4ou9rb7i0btcccitabgpebi.apps.googleusercontent.com',
    iosBundleId: 'com.example.sangathan',
  );
}
