class Constants {
  static const double paddingRight = 19;
  static const double paddingLeft = 19;
  static const double buttonLeft = 71;
  static const double buttonRight = 71;
  static const double buttonSizeBoxWidth = 218;
  static const double buttonSizeBoxHeight = 45;
  static const List stateListN = [

  ];
  static const List acList = [
    "Abhayapuri North",
    "Abhayapuri South",
    "Algapur",
    "Amguri",
    "Badarpur",
    "Baghbar",
    "Baithalangso",
    "Barama",
    "Barchalla",
    "Barhampur",
    "Barkhetry",
    "Barkhola",
    "Barpeta",
    "Batadroba",
    "Behali",
    "Bhabanipur",
    "Bihpuria",
    "Bijni",
    "BILASIPARA EAST",
    "BILASIPARA WEST",
    "Biswanath",
    "Bokajan",
    "Bokakhat",
    "Boko SC",
    "Bongaigaon",
    "Chabua",
    "Chapaguri",
    "Chaygaon",
    "Chenga",
    "Dalgaon",
    "Dergaon",
    "Dhakuakhana",
    "Dharmapur",
    "Dhekiajuli",
    "Dhemaji",
    "Dhing",
    "Dholai",
    "Dhubri",
    "Dibrugarh",
    "Digboi",
    "Diphu",
    "Dispur",
    "Doom Dooma",
    "Dudhnai",
    "Duliajan",
    "Gauhati East",
    "Gauhati West",
    "Gauripur",
    "Goalpara East",
    "Goalpara West",
    "Gohpur",
    "Golaghat",
    "Golakganj",
    "Gossaigaon",
    "Guwahati",
    "Haflong",
    "Hailakandi",
    "Hajo",
    "Haladharbond",
    "Hamren",
    "Harisinga",
    "Hojai",
    "Howly",
    "Jagiroad",
    "Jalukbari",
    "Jania",
    "Jorhat",
    "Kabibari",
    "Kahilipara",
    "Kalgachia",
    "Kalibari",
    "Kaliabor",
    "Kamalpur",
    "Kampur",
    "Karbi Anglong West",
    "Karimganj North",
    "Karimganj South",
    "Katigorah",
    "Kokrajhar East",
    "Kokrajhar West",
    "Lahowal",
    "Lakhipur",
    "Lankeshwar",
    "Lapodia",
    "Lumding",
    "Majbat",
    "Makum",
    "Mangaldoi",
    "Margherita",
    "Mariani",
    "Marigaon",
    "Marksachu",
    "Moran",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Naoboicha",
    "Rangapara",
    "Rangiya",
    "Rongpur",
    "Rupohihat",
    "Sadiya",
    "Sailajanagar",
    "Sakti",
    "Salmara South",
    "Sapatgram",
    "Sarukhetri",
    "Sarupathar",
    "Sibsagar",
    "Siddipet",
    "Sonari",
    "Sootea",
    "Sualkuchi",
    "Tamulpur",
    "Tanka Bhaban",
    "Tezpur",
    "Tingkhong",
    "Tinsukia",
    "Titabor",
    "Udalguri",
    "Udharbond"
  ];
}
